// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhrbbudlqvzugynpeuoj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhocmJidWRscXZ6dWd5bnBldW9qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyODY0NDgsImV4cCI6MjA2Mzg2MjQ0OH0.ztIYIWgYmOHgTyZ6R6zKFZ-s3P-evM19_DZVX-c48PY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);